### ISSUE TITLE
gin的例子 在执行s deploy 后报错

### ISSUE THREAD

**Issue by mingcode100** [devsapp/start-web-framework#129]
使用的工具版本是3，在这个文档里找的安装方法 https://docs.serverless-devs.com/serverless-devs/install

工程是使用`s init start-gin`创建的

报错内容
```
× read ECONNRESET
✖ Generated custom domain (6.96s)
✖ Generated domain (7.8s)

Error Message:
{"code":101,"message":"Url:http://domain.devsapp.net/token\n,params: {\"method\":\"post\",\"body\":{\"type\":\"fc\",\"user\":\"1606212852264867\",\"region\":\"cn-hangzhou\",\"service\":\"web-framework-n5fd\",\"function\":\"gin\"},\"form\":true}\n,ErrorMessage:read ECONNRESET\n, Code: undefined","stack":"Error: Url:http://domain.devsapp.net/token\n,params: {\"method\":\"post\",\"body\":{\"type\":\"fc\",\"user\":\"1606212852264867\",\"region\":\"cn-hangzhou\",\"service\":\"web-framework-n5fd\",\"function\":\"gin\"},\"form\":true}\n,ErrorMessage:read ECONNRESET\n, Code: undefined\n    at C:\\Users\\liuyu\\.s\\cache\\core\\dist\\index.js:81:461\n    at l (C:\\Users\\liuyu\\.s\\cache\\core\\dist\\index.js:78:13483)\n    at Object.throw (C:\\Users\\liuyu\\.s\\cache\\core\\dist\\index.js:78:12787)\n    at l (C:\\Users\\liuyu\\.s\\cache\\core\\dist\\index.js:78:12395)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","prefix":"Project framework failed to execute:"}
```

**Comment by mingcode100** [comment]
解决了，在钉钉群里，听大佬的去掉自定义域名配置
