### ISSUE TITLE
为什么官方钉钉客服说云端构建不支持docker镜像

### ISSUE THREAD

**Issue by wanghaisheng** [devsapp/start-web-framework#46]
https://github.com/devsapp/start-web-framework/tree/master/web-framework/python/fastapi/src
以此例来说，就有直接pip安装和dockerfile两种
我自己用dockerfile异常，pip的话阿里云的镜像压根找不到supabase这个包
@anycodes

**Comment by wanghaisheng** [comment]
```
certifi==2021.10.8
charset-normalizer==2.0.11
click==8.0.3
colorama==0.4.4
Flask==2.0.2
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
pywebio==1.5.2
retrying==1.3.3
six==1.16.0
tornado==6.1
ua-parser==0.10.0
urllib3==1.26.8
user-agents==2.2.0
Werkzeug==2.0.2
gunicorn
pyscreenshot
lazyEdge
requests
selenium_stealth
selenium
pillow
pandas
plane
undetected-chromedriver
opencv-python-headless
numpy
sentry-sdk
environs
cachetools
psycopg2-binary 
pytz
webdriver_manager
fastapi-cloudauth
python-firebase
firebase-admin
supabase
playwright==1.18.1
python-dotenv
tenacity==8.0.1
```

**Comment by anycodes** [comment]
卡住的原因是，你依赖太多了。应该是在执行中，并没有卡住。
你可以发一些截图，描述一下你判断卡住的依据

**Comment by wanghaisheng** [comment]
@anycodes 
```

  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/60/2e/dec1cc18c51b8df33c7c4d0a321b084cf38e1733b98f9d15018880fb4970/pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting webdriver_manager
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c5/75/ed5b098c7ccef65c29c005cd817a41cd3fead5ddab97a254bb2ad817df9c/webdriver_manager-3.5.4-py2.py3-none-any.whl (18 kB)
Collecting fastapi-cloudauth
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e6/18/552e2b5e984a9cea10059b69294daa1ada66113d0b2212d02027e6c81491/fastapi_cloudauth-0.4.3-py3-none-any.whl (14 kB)
Collecting python-firebase
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/32/e6/88b799753e64aeb0f24040b98c94012994cf9517c889dee4f8a49ac89400/python-firebase-1.2.tar.gz (10 kB)
Collecting firebase-admin
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8b/07/437c61ea8f597c22cfe9bd801484ab9e449d7c16f8ec50fcf8d18f421c74/firebase_admin-5.2.0-py3-none-any.whl (115 kB)
ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
✖ Message:

ERROR:

Error: Command failed with exit code 1: pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
    at makeError (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/execa/index.js:194:17)
    at Hook.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:147:49)
    at step (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:44:23)
    at Object.next (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:25:53)
    at /usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:15:12)
    at Hook.commandExecute (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:139:16)
    at Hook.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:92:51)
TraceId:     96cbc71d96041651753274084
```
比如这种 本地的话 lib安装完全没问题 但放上去就no match version
