### ISSUE TITLE
--use-docker 未生效

### ISSUE THREAD

**Issue by wanghaisheng** [devsapp/start-web-framework#48]
```
2022-05-12 23:25:34 INFO b06b9aea-3cb9-499a-8545-c4ba62088293 - FC Invoke Start RequestId: 1652397934637000
2022-05-12 23:25:34 INFO b06b9aea-3cb9-499a-8545-c4ba62088293 - Begin to use Serverless Devs to deploy ...
2022-05-12 23:25:34 INFO b06b9aea-3cb9-499a-8545-c4ba62088293 - Execute command: s  deploy, args: ["--access 1652397915390000","--use-local","--assume-yes","--skip-push"]


[2022-05-12 23:25:35] [INFO] [S-CORE] - Start the pre-action
[2022-05-12 23:25:35] [INFO] [S-CORE] - Action: pip install --upgrade pip
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.2.4)
Collecting pip
  Downloading https://mirrors.aliyun.com/pypi/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2022-05-12 23:25:39] [INFO] [S-CORE] - Action: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting postgrest-py==0.10.2
  Downloading https://github.com/supabase-community/postgrest-py/releases/download/v0.10.2/postgrest_py-0.10.2-py3-none-any.whl (15 kB)
Collecting supabase==0.5.5
  Downloading https://github.com/supabase-community/supabase-py/releases/download/v0.5.5/supabase-0.5.5-py3-none-any.whl (9.8 kB)
Collecting playwright==1.21.0
  Downloading playwright-1.21.0-py3-none-manylinux1_x86_64.whl (33.4 MB)
Collecting certifi==2021.10.8
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.11
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0c/8e/73ef5366e5c04c2410dab1c74493ca9617a56a27a50f11e01aa4fac2a16c/charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
Collecting click==8.0.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl (97 kB)
Collecting colorama==0.4.4
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting Flask==2.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8f/b6/b4fdcb6d01ee20f9cfe81dcf9d3cd6c2f874b996f186f1c0b898c4a59c04/Flask-2.0.2-py3-none-any.whl (95 kB)
Collecting itsdangerous==2.0.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/96/26f935afba9cd6140216da5add223a0c465b99d0f112b68a4ca426441019/itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting MarkupSafe==2.0.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e2/a9/eafee9babd4b3aed918d286fbe1c20d1a22d347b30d2bddb3c49919548fa/MarkupSafe-2.0.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting pywebio==1.5.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/25/1f/df070eb83465bd38f7393b006ded995442e4297a1dcee2988e1c13317f7a/pywebio-1.5.2.tar.gz (450 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting retrying==1.3.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six==1.16.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (1.16.0)
Collecting tornado==6.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/85/26/e710295dcb4aac62b08f22d07efc899574476db37532159a7f71713cdaf2/tornado-6.1-cp36-cp36m-manylinux2010_x86_64.whl (427 kB)
Collecting ua-parser==0.10.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9d/22/4d16b08db329fd440eed366d35e4dd7195c9babb4ecac5218f28081522a2/ua_parser-0.10.0-py2.py3-none-any.whl (35 kB)
Collecting user-agents==2.2.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8f/1c/20bb3d7b2bad56d881e3704131ddedbb16eb787101306887dff349064662/user_agents-2.2.0-py3-none-any.whl (9.6 kB)
Collecting Werkzeug==2.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1e/73/51137805d1b8d97367a8a77cae4a792af14bb7ce58fbd071af294c740cf0/Werkzeug-2.0.2-py3-none-any.whl (288 kB)
Collecting gunicorn
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e4/dd/5b190393e6066286773a67dfcc2f9492058e9b57c4867a95f1ba5caf0a83/gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting requests
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting selenium==3.141.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting undetected-chromedriver==3.0.6
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d0/f5/c2857fb8d446a3f258505f94c8ceac0dfb7898c56bd5b0d430961f5f2ea6/undetected-chromedriver-3.0.6.tar.gz (51 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pillow==8.3.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/cc/e2/31c6ee4acc116b65c40badc4a6eeb38e7cdb697c0e9a365397de52d17c08/Pillow-8.3.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting pandas==1.1.4
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4d/51/bafcff417cd857bc6684336320863b5e5af280530213ef8f534b6042cfe6/pandas-1.1.4-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
Collecting plane==0.2.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/40/d6/0eabf619f7f143465bf1d6918467201c10e3a6e0d461e2a44ae8dcc690ba/plane-0.2.0-py2.py3-none-any.whl (10 kB)
Collecting opencv-python-headless==4.5.5.62
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7e/05/a3c67e6a2f6ae471941dbe556f3cd7b605adfb3eb7272bf4cbf89eacb97e/opencv_python_headless-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (47.7 MB)
Collecting numpy==1.19.4
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/87/86/753182c9085ba4936c0076269a571613387cdb77ae2bf537448bfd63472c/numpy-1.19.4-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
Collecting sentry-sdk==1.5.10
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/28/3c/d93dcff24ae034006baf1686a55764ada9bf3ae572ae2f190a41f15c8366/sentry_sdk-1.5.10-py2.py3-none-any.whl (144 kB)
Collecting environs==9.4.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/88/a1/d88630980f6800bd8bcc34e9aa3717cbc0209ea1df83a12b0b740f636bd1/environs-9.4.0-py2.py3-none-any.whl (12 kB)
Collecting cachetools==4.2.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/12/09/64bfb4ae6624248f1ceac7474bb9088ff6fe912f1ee050393cb17bb910f0/cachetools-4.2.3-py3-none-any.whl (8.6 kB)
Collecting psycopg2-binary==2.9.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e9/ad/03e2ec00d4047171729965ac65ba85c2ca0f85497468a20bd0024b4862d4/psycopg2_binary-2.9.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting pytz
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/60/2e/dec1cc18c51b8df33c7c4d0a321b084cf38e1733b98f9d15018880fb4970/pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting webdriver_manager==3.5.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/74/13/6ac33902d7c4dc012207876ef6e42d49a8b8202a6a83d69d139430249ed6/webdriver_manager-3.5.2-py2.py3-none-any.whl (17 kB)
Collecting fastapi-cloudauth==0.4.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ab/03/2b3dab25f3ed86b8a728712a23504416d61d33d60b63e5a2d1784d0217b1/fastapi_cloudauth-0.4.2-py3-none-any.whl (14 kB)
Collecting python-firebase
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/32/e6/88b799753e64aeb0f24040b98c94012994cf9517c889dee4f8a49ac89400/python-firebase-1.2.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting firebase-admin==5.1.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/61/dc/15a2a7d5ed6438693226a2d09c02d0c1c750d6d43fb6231024787136eb28/firebase_admin-5.1.0-py3-none-any.whl (114 kB)
Collecting python-dotenv
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/30/5f/2e5c564bd86349fe6b82ca840f46acf6f4bb76d79ba9057fce3d3e008864/python_dotenv-0.20.0-py3-none-any.whl (17 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from click==8.0.3->-r requirements.txt (line 3)) (4.8.3)
Collecting Jinja2>=3.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/20/9a/e5d9ec41927401e41aea8af6d16e78b5e612bca4699d417f646a9610a076/Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting dataclasses
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting urllib3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/03/062e6444ce4baf1eac17a6a0ebfe36bb1ad05e1df0e20b110de59c278498/urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting websockets
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/a4/38eb0bc75fb6ea61dc54d5131286d1f474abc83de89cb6e217fb9e244570/websockets-9.1-cp36-cp36m-manylinux2010_x86_64.whl (102 kB)
Collecting python-dateutil>=2.7.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting marshmallow>=3.0.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/f3/62015688fdb1e02779702c36e500a123e019a4f99a70fd849de2c7572748/marshmallow-3.14.1-py3-none-any.whl (47 kB)
Collecting configparser
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2b/af/0e28626b47c84172a112397f034bb1b6349960ca6e0fe7c96666e0ccae69/configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting crayons
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5b/0d/e3fad4ca1de8e70e06444e7d777a5984261e1db98758b5be3e8296c03fe9/crayons-0.4.0-py2.py3-none-any.whl (4.6 kB)
Collecting python-jose[cryptography]<4.0.0,>=3.3.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bd/2d/e94b2f7bab6773c70efc70a61d66e312e1febccd9e0db6b9e0adf58cbad1/python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
Collecting fastapi<1.0,>=0.60.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/16/5b/d45cca598cec06bead962b84648cbdb0c0d966f2453694bce6f5ce4c0bc9/fastapi-0.77.1-py3-none-any.whl (54 kB)
Collecting cachecontrol>=0.12.6
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/83/63/15ce47ede5b03657e920f3f006e56ca9a16f7873978146f2f77e297bdd22/CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)
Collecting google-cloud-storage>=1.37.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/82/b9/c31cfed0024c5929f0d27d13e2879d8ed9c67d37b0a85cb72de8dc3a6fa5/google_cloud_storage-2.0.0-py2.py3-none-any.whl (106 kB)
Collecting google-api-core[grpc]<3.0.0dev,>=1.22.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e9/88/6e9c4940ac46dbc772403309dc9b671e10ae4ba4e87f3595537caa822d53/google_api_core-2.7.3-py3-none-any.whl (114 kB)
Collecting google-api-python-client>=1.7.8
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ca/38/83527c29fe80a138942db73c7905324e57e0d93fc30e526f870788853bc4/google_api_python_client-2.47.0-py2.py3-none-any.whl (8.4 MB)
Collecting google-cloud-firestore>=2.1.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b4/50/a2b542047e20a9dc69359755ed241b7f518f0785e69153ad08995912e36b/google_cloud_firestore-2.4.0-py2.py3-none-any.whl (243 kB)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.6/site-packages (from gunicorn->-r requirements.txt (line 15)) (57.5.0)
Collecting idna<4,>=2.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61 kB)
Collecting deprecation<3.0.0,>=2.1.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/02/c3/253a89ee03fc9b9682f1541728eb66db7db22148cd94f89ab22528cd1e1b/deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting pydantic<2.0.0,>=1.9.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/97/9a/00dbc8a835eab9b271a6b09af2b2e66ea1e429c4523aa90ca2ceac0646d9/pydantic-1.9.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.0 MB)
Collecting httpx<0.23,>=0.20
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/2f/d3/6a990516a43a522a72da356c4a91c03e09c0cddce8106e7e1215c120011f/httpx-0.22.0-py3-none-any.whl (84 kB)
INFO: pip is looking at multiple versions of python-firebase to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytz to determine which version is compatible with other requirements. This could take a while.
Collecting pytz
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl (503 kB)
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
Collecting requests
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/01/f420e7add78110940639a958e5af0e3f8e07a8a8b62049bac55ee117aa91/requests-2.27.0-py2.py3-none-any.whl (63 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/92/96/144f70b972a9c0eabbd4391ef93ccd49d0f2747f4f6a2a2738e99e5adc65/requests-2.26.0-py2.py3-none-any.whl (62 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting idna<3,>=2.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting requests
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting chardet<4,>=3.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting requests
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting urllib3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
INFO: pip is looking at multiple versions of gunicorn to determine which version is compatible with other requirements. This could take a while.
Collecting gunicorn
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e4/cc/e29ede47f5591245e7a343ffa541d250ae51ba136bb9a7e8fe6d1bb24803/gunicorn-20.0.3-py2.py3-none-any.whl (79 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4c/f4/1fff9549bda65801f34bd02a86bde95c945401bfc21cc9cb9e35ec790ba5/gunicorn-20.0.2-py2.py3-none-any.whl (115 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/60/0d/3dbda0324f5bf007f3274e5ea09f0f3bcbf0ca01a75b80ff4f1ff9f8ecfd/gunicorn-20.0.0-py2.py3-none-any.whl (77 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5f/54/c15f2c243c19074cbf06ce6c48732d99aec825487f87e57e86e9a22990f2/gunicorn-19.10.0-py2.py3-none-any.whl (113 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/55/cb/09fe80bddf30be86abfc06ccb1154f97d6c64bb87111de066a5fc9ccb937/gunicorn-19.8.1-py2.py3-none-any.whl (112 kB)
INFO: pip is looking at multiple versions of gunicorn to determine which version is compatible with other requirements. This could take a while.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ba/a9/67db283e31084925e5b1943a724965f0320577bfdc5144175b64d4328df0/gunicorn-19.8.0-py2.py3-none-any.whl (112 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/64/32/becbd4089a4c06f0f9f538a76e9fe0b19a08f010bcb47dcdbfbc640cdf7d/gunicorn-19.7.1-py2.py3-none-any.whl (111 kB)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/96/4b/bc4bc2dad60defaa3f7d8590dc51331a225a5399380c161047c1224cd86d/gunicorn-19.7.0-py2.py3-none-any.whl (112 kB)
INFO: pip is looking at multiple versions of firebase-admin to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of fastapi-cloudauth to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of webdriver-manager to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of psycopg2-binary to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cachetools to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of environs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of sentry-sdk to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of opencv-python-headless to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of plane to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pillow to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of undetected-chromedriver to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of selenium to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of werkzeug to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of user-agents to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ua-parser to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tornado to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
Collecting six==1.16.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
INFO: pip is looking at multiple versions of retrying to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'postgrest-py' requires a different Python: 3.6.15 not in '<4.0,>=3.7'
INFO: pip is looking at multiple versions of pywebio to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of markupsafe to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of itsdangerous to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of colorama to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of click to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
✖ Message:

ERROR:

Error: Command failed with exit code 1: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
    at makeError (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/execa/index.js:194:17)
    at Hook.<anonymous> (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:147:49)
    at step (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:44:23)
    at Object.next (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:25:53)
    at /root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:15:12)
    at Hook.commandExecute (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:139:16)
    at Hook.<anonymous> (/root/.nvm/versions/node/v14.19.2/lib/node_modules/@serverless-devs/s/node_modules/@serverless-devs/core/dist/common/execCommand/component/hook.js:92:51)
2022-05-12 23:26:17 ERROR b06b9aea-3cb9-499a-8545-c4ba62088293 - Failed to deploy, errorMsg:[]
TraceId:     0a3ff14222fc1652397977204
```

services:
  framework: # 业务名称/模块名称
    # 如果只想针对 framework 下面的业务进行相关操作，可以在命令行中加上 framework，例如：
    # 只对framework进行构建：s framework build
    # 如果不带有 framework ，而是直接执行 s build，工具则会对当前Yaml下，所有和 framework 平级的业务模块（如有其他平级的模块，例如下面注释的next-function），按照一定顺序进行 build 操作
    component: fc # 组件名称，Serverless Devs 工具本身类似于一种游戏机，不具备具体的业务能力，组件类似于游戏卡，用户通过向游戏机中插入不同的游戏卡实现不同的功能，即通过使用不同的组件实现不同的具体业务能力
    actions:       # 自定义执行逻辑，关于actions 的使用，可以参考：https://www.serverless-devs.com/serverless-devs/yaml#行为描述
      pre-deploy: # 在deploy之前运行
        - component: fc build --use-docker --dockerfile ./Dockerfile           # 要运行的组件，格式为【component: 组件名 命令 参数】（可以通过s cli registry search --type Component 获取组件列表）
        - run: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt  # 要执行的系统命令，类似于一种钩子的形式
          path: ./                                    # 执行系统命令/钩子的路径
        - run: playwright install
#        - plugin: myplugin                               # 与运行的插件 （可以通过s cli registry search --type Plugin 获取组件列表）
#          args:                                          # 插件的参数信息
#            testKey: testValue
      post-deploy: # 在deploy之后运行
        - run: python app.py

**Comment by anycodes** [comment]
- plugin: myplugin # 与运行的插件 （可以通过s cli registry search --type Plugin 获取组件列表）

已经修复
